# Generated by Django 3.2.9 on 2021-12-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body_temparature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='day',
            field=models.DateField(auto_now_add=True, verbose_name='日付'),
        ),
    ]
